version: '3.8'

services:
  dynamodb-local:
    networks:
      - sam
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ".:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root

networks:
  sam:
    name: sam-network