version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "email-text-reminders"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8yl96q7crrb0"
s3_prefix = "email-text-reminders"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
